IKO-FinalProject/FE-Client

src/components/auth/hooks/useAuth.tsx, src/components/auth/hooks/useUser.tsx, src/components/axiosinstance/index.ts, src/components/common/hooks/useToast.tsx, src/components/local-storage/userStorage.ts, src/components/react-query/queryClient.ts, src/components/react-query/queryKeys.ts, src/pages/Main.tsx
- queryClient의 export 누락 수정 및 queryErrorHandler function에 useToast를 적용하여 failed message를 출력할 수 있게끔 만들었습니다.
=> style: export 누락 및 queryErrorhandler toast 적용

src/components/auth/hooks/useAuth.tsx, src/components/auth/hooks/useUser.tsx, src/components/auth/types/userTypes.ts, src/pages/Main.tsx
- user 타입 변경
- types 파일을 따로 만들어 type을 분리하였습니다.
=> chore: 유저 프로퍼티 타입 변경

src/components/ProductDetail/ProductTabs.tsx, src/components/favorite/AllFavoriteList.tsx, src/components/favorite/FavoriteList.tsx, src/components/favorite/MonthlyFavorite.tsx, src/components/favorite/OneDay.tsx, src/components/favorite/OneDayFavorite.tsx, src/components/favorite/OneMonth.tsx, src/pages/Favorite.tsx, src/routes/router.tsx
- 즐겨찾기(찜) 페이지 퍼블리싱
- 라우터로 탭 구현
=> feat: #48 즐겨찾기(찜) 페이지 퍼블리싱

src/components/common/SwiperButton.tsx, src/components/review/RevieItems.tsx, src/components/review/ReviewBanner.tsx, src/components/review/ReviewContainer.tsx, src/components/review/ReviewDetails.tsx, src/pages/ReviewPage.tsx, src/routes/router.tsx
- 리뷰 페이지 퍼블리싱
- shadow 적용, 페이지네이션, 리뷰 상세페이지
=> #42 리뷰 페이지 퍼블리싱

src/components/main/notice/utils/MobileNotice.tsx, src/pages/Main.tsx
className 카멜 케이스로 변경
- 내용을 적어주세요.
- 내용을 적어주세요.
=> chore: 카멜 케이스 변경

public/assets/plus.svg, src/components/ProductDetail/ProductDetails.tsx, src/components/review/RevieItems.tsx, src/components/review/ReviewBanner.tsx, src/pages/ReviewPage.tsx, tailwind.config.cjs
- 내용을 적어주세요.
- 리뷰 토글기능
- shadow, drop-shadow config에 설정
=> feat: review toggle & shadow drop-shadow 설정

src/components/review/RevieItems.tsx, src/components/review/ReviewContainer.tsx, src/components/review/mobile/ReviewMobileBanner.tsx, src/pages/ReviewPage.tsx, tailwind.config.cjs
리뷰 모바일 페이지 제작
- 스와이퍼
- xs-max설정
=> feat: 리뷰 모바일 페이지

src/components/ProductDetail/ProductBanner.tsx, src/components/ProductDetail/ProductDetails.tsx, src/components/ProductDetail/ProductInfo.tsx, src/components/ProductDetail/ProductRecommend.tsx, src/components/ProductDetail/ProductTabs.tsx, src/components/ProductDetail/mobile/MobileProductRecommend.tsx
=> feat: #73 제품 상세 모바일

src/components/Banner.tsx, src/components/header/Header.tsx, src/components/main/filterbar/common/BoxLayout.tsx, src/components/main/filterbar/common/MobileBoxLayout.tsx, src/components/main/filterbar/mobile/MobileFilter.tsx, src/constants/filterData.ts, src/main.tsx, src/pages/Favorite.tsx, src/pages/Main.tsx, src/store/filterOpen.ts, src/store/filterVallue.ts, tailwind.config.cjs
- 모바일 필터 구현
- 모바일 필터 퍼블리싱
- 헤더에 필터 버튼 누르면 필터 open
- recoile 적용
=> feat: 모바일 필터 구현

src/components/common/CartAndHeart.tsx, tailwind.config.cjs
- 하트 & 카트 애니메이션 추가
- 내용을 적어주세요.
- 내용을 적어주세요.
=> feat: 하트와 카트 애니메이션

src/components/main/filterbar/FilterBar.tsx, src/components/main/filterbar/common/MobileBoxLayout.tsx, src/components/main/filterbar/mobile/MobileFilter.tsx, src/constants/filterData.ts, src/store/filterVallue.ts
- 필터 값 리코일로 상태 관리
- 필터 값 누적, 토글 기능
#76
=> feat: 필터 값 리코일로 상태 관리 - 누적

index.html
=> fix: 배포시 로그인 mixed content 에러 수정

src/components/common/ui/PageLayout.tsx, src/components/common/util/cls.ts, src/components/main/filterbar/FilterBar.tsx, src/components/main/filterbar/FilterButtons.tsx, src/components/main/filterbar/mobile/MobileFilter.tsx
- FilterBar Refresh 버튼 클릭시 atom 상태 초기화
- useResetRecoilState 활용하여 atom 상태 초기화
=> feat: refresh 버튼 클릭시 atom 상태 reset

src/components/common/Card.tsx
=> feat: 상품 -> 제품 상세 navigate 임시 적용

src/components/main/CardContainer.tsx
페이지 값 수정 및 메인 페이지네이션 껍데기 추가
- 내용을 적어주세요.
- 내용을 적어주세요.
=> chore: 페이지 값 수정

src/components/common/Card.tsx, src/components/main/CardContainer.tsx, src/components/main/hooks/useProductLists.ts, src/pages/Main.tsx
- 내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
=> chore: 그래픽 직경 number 변경

src/components/main/recommend/RecommendBanner.tsx, src/pages/Main.tsx
- 추천 배너 스타일 수정 및 배너 사진 변경
- 내용을 적어주세요.
- 내용을 적어주세요.
=> style: 추천 배너 스타일 수정 및 배너 사진 변경

src/components/EventDetail.tsx, src/components/main/CardContainer.tsx, src/components/main/common/Pagination.tsx, src/components/main/hooks/useProductLists.ts, src/components/main/notice/NoticeDetail.tsx, src/pages/Main.tsx
- 내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
=> feat: 프리페치 함수 구현, 공지사항 디테일 디자인 수정

src/components/ProductDetail/ProductDetails.tsx
- 페이지 이동시 스크롤이동
- 제품상세 페이지 이동시 스크롤 최상단으로 이동시키기
=> feat: 제품상세 페이지 진입시 스크롤 최상단으로 이동

src/components/favorite/AllFavoriteList.tsx, src/pages/Main.tsx
- 타입 수정 및 배너 클릭 시 퍼스널 컬러 테스트 페이지로 이동
- 내용을 적어주세요.
- 내용을 적어주세요.
=> fix: 타입 수정 및 배너 클릭 시 퍼스널 컬러 테스트 페이지로 이동

src/components/cart/hooks/useCart.tsx, src/components/common/CartAndHeart.tsx, src/components/main/hooks/useFavorite.ts
- 내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
=> feat: 토스트 추가

src/components/ProductDetail/ProductInfo.tsx
- 내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
=> fix: 닫기 버튼 렌더 조건 추가

src/components/common/CartAndHeart.tsx, src/components/main/CardContainer.tsx, src/components/main/MainCartModal.tsx, src/store/mainCart.ts
- 내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
=> feat: 사용자 즐겨찾기 불러와서 반영 구현

src/components/common/Card.tsx, src/components/common/CartAndHeart.tsx
- 내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
=> fix: 카트앤하트 타입 에러 수정 및 카드 컬러 스타일 수정

src/components/Banner.tsx, src/components/ProductDetail/ProductDescription.tsx, src/components/ProductDetail/ProductDetails.tsx, src/components/ProductDetail/ProductInfo.tsx, src/components/ProductDetail/ProductTabs.tsx, src/components/ProductDetail/hooks/useProductDetails.tsx, src/components/cart/hooks/useCart.tsx, src/components/event/MainEvent.tsx, src/components/favorite/AllFavoriteList.tsx, src/components/favorite/MonthlyFavorite.tsx, src/components/favorite/OneDayFavorite.tsx, src/components/main/CardContainer.tsx, src/components/main/filterbar/FilterBar.tsx, src/components/main/filterbar/FilterButtonFunction.tsx, src/components/main/filterbar/FilterButtons.tsx, src/components/main/hooks/useBanner.ts, src/components/main/hooks/useFavorite.ts, src/components/main/types/productTypes.ts, src/pages/Main.tsx, src/pages/ProductDetail.tsx, src/store/filterVallue.ts, src/store/productByOptions.ts
- 다중 필터 기능, 제품상세 옵션 선택, 장바구니 추가
- 다중 필터 기능, 제품상세 옵션 선택, 장바구니 추가
=> GyeongChan

src/components/Banner.tsx, src/components/EventDetail.tsx, src/components/main/CardContainer.tsx, src/components/main/common/Pagination.tsx, src/components/main/hooks/useBanner.ts, src/components/main/hooks/useEventLists.ts, src/components/main/hooks/useNotice.ts, src/components/main/notice/NoticeDetail.tsx, src/components/main/notice/NoticeTitle.tsx, src/components/main/notice/pages/AboutCredit.tsx, src/components/main/notice/pages/AboutEtc.tsx, src/components/main/notice/pages/AboutMustRead.tsx, src/components/main/notice/pages/AboutPoint.tsx, src/components/main/notice/pages/AboutProduct.tsx, src/components/main/notice/pages/AboutRefund.tsx, src/components/main/notice/pages/AboutShip.tsx, src/components/main/notice/tabs/NoticePageTab.tsx, src/components/main/notice/utils/MobileNotice.tsx, src/components/main/notice/utils/WebNotice.tsx, src/components/main/types/eventTypes.ts, src/components/main/types/noticeTypes.ts, src/components/react-query/queryKeys.ts, src/pages/NoticePage.tsx
공지사항 및 이벤트 함수 변경 및 검색 필터 grid 변경
=> fix: 공지사항 및 이벤트 함수 수정 및 검색 필터 grid 수정

src/components/ProductDetail/ProductInfo.tsx, src/components/common/Card.tsx, src/components/main/CardContainer.tsx, src/components/main/hooks/useFavorite.ts, src/components/main/hooks/useNotice.ts, src/components/main/hooks/useProductLists.ts, src/components/main/notice/NoticeDetail.tsx, src/components/main/notice/pages/AboutMustRead.tsx, src/components/main/notice/utils/MobileNotice.tsx, src/components/main/types/noticeTypes.ts, src/pages/Main.tsx
- 내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
=> feat: 콤마 수정 및 메인 렌더링 시 유저 정보 넣어줘야함

src/components/footer/bottom-navigation/MobileBottomNav.tsx, src/components/main/hooks/useEventLists.ts, src/components/main/hooks/useNotice.ts, src/components/main/notice/NoticeDetail.tsx, src/components/main/notice/pages/AboutCredit.tsx, src/components/main/notice/pages/AboutEtc.tsx, src/components/main/notice/pages/AboutMustRead.tsx, src/components/main/notice/pages/AboutPoint.tsx, src/components/main/notice/pages/AboutProduct.tsx, src/components/main/notice/pages/AboutRefund.tsx, src/components/main/notice/pages/AboutShip.tsx, src/components/main/notice/utils/MobileNotice.tsx, src/components/main/notice/utils/WebNotice.tsx, src/components/main/types/eventTypes.ts, src/components/main/types/noticeTypes.ts, src/pages/EventPage.tsx
- 내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
=> feat: 상단 노출 이벤트 구현

src/components/EventDetail.tsx, src/pages/EventPage.tsx
- 내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
=> feat: 모바일 상단 노출 추가

src/components/main/hooks/useNotice.ts, src/components/main/notice/pages/AboutMustRead.tsx, src/components/main/notice/pages/AboutPoint.tsx, src/components/main/notice/pages/AboutProduct.tsx, src/components/main/notice/pages/AboutRefund.tsx, src/components/main/notice/pages/AboutShip.tsx
- 내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
=> fix: 타입 에러 수정

src/pages/EventPage.tsx
- 내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
=> fix: 이벤트디테일 타입에러 수정

package-lock.json, package.json, src/components/review/ReviewForm.tsx, src/pages/EventPage.tsx
=> fix: 배포에러 react-aws-s3-typescirpt import 방식 변경

src/components/ProductDetail/ProductInfo.tsx
fix: 장바구니 추가 눌렀을 때 불리언 값 false 로 변경
=> fix: 장바구니 추가 눌렀을 때 불리언 값 false 로 변경

src/components/review/ReviewForm.tsx
- 내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
=> fix: console 코드 제거 및 aws 파일 제거
